name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set ROOT_URL secret as an environment variable
      env:
        TOKEN: ${{ secrets.TOKEN }}
      uses: mxschmitt/action-tmate@v3
