name: ss
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: update pass
      run: |
          echo "runner:1qaz@WSX" | sudo chpasswd
    
    - name: Set ROOT_URL secret as an environment variable
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb && sudo cloudflared service install $TOKEN
    - name: hold
      run: |
        tail -f /etc/hosts
